# Generated by Django 4.1.3 on 2023-02-14 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student_subjects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subname', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='Cname',
        ),
        migrations.AlterField(
            model_name='class',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='student_subjects',
            name='subject_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='class_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
